project:
  type: book
  resources:
    - data/**

execute-dir: project
filters:
  - filters/last-figure-image.lua

book:
  title: "charlotte.computer"
  chapters:
    - index.qmd
    - topics/perceptrons.ipynb
    - topics/convolutional-neural-networks.ipynb
    - topics/tokenization.ipynb
    - topics/linear-regression.ipynb
    - books.qmd
    - papers.qmd
    - courses.qmd
    - resources.qmd
    - datasets.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
